# X11 display server configuration
# Requires: xhost +SI:localuser:$USER

services:
  tlauncher:
    environment:
      DISPLAY: ${DISPLAY}
      XAUTHORITY: /tmp/.Xauthority
      XDG_RUNTIME_DIR: /run/user/1000

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - ${XAUTHORITY}:/tmp/.Xauthority:ro
